# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 11:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ImageField(upload_to='user', verbose_name='用户的头像')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误!')], verbose_name='手机号码'),
        ),
    ]
