# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_user', '0002_auto_20180923_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='head',
            field=models.ImageField(default='user/201809/23/tx1.png', upload_to='head/%Y/%m', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='testimagemodel',
            name='head',
            field=models.ImageField(upload_to='user/%Y%m/%d', verbose_name='用户的头像'),
        ),
    ]
